### ISSUE TITLE
Don't work Cozy Nest Image Browser

### ISSUE THREAD

**Issue by Nekich3112** [Nevysha/Cozy-Nest#100]
Don't work Cozy Nest Image Browser. After I click "connect" nothing happens. I tried to open Chrome, Firefox and Edge browsers
![cos](https://github.com/Nevysha/Cozy-Nest/assets/20690061/cb2165cc-a8b0-498d-88e3-8c331beeefc2)

**Comment by VelvetAcidChrist** [comment]
You just haven't generated any pictures with Cozy Browser yet, so you don't have any pictures in it.

**Comment by Nevysha** [comment]
> You just haven't generated any pictures with Cozy Browser yet, so you don't have any pictures in it.

No the image browser should display image in the output folder. What are the output folder you have set in the a1111 settings ?

**Comment by Nekich3112** [comment]
![image](https://github.com/Nevysha/Cozy-Nest/assets/20690061/7987d1e0-4c79-4d2b-81b3-091ecedbda51)
![image](https://github.com/Nevysha/Cozy-Nest/assets/20690061/fc390016-07cb-4624-bb47-07cf5321c771)
folders have 3k+ pictures generated with installed Cozy Nest

**Comment by Nevysha** [comment]
@Nekich3112 Thanks for the feedback

Any error in the Automatic's output ? Or in the Browser console ?
