### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#106]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/3e74eaf6-aa9b-4983-8715-787a7cd33914)

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/1231707b-3180-4045-bfe1-154ed6fa1b1d)

**Comment by Nevysha** [comment]
should be fixed now (need to update through extension tab)
