### ISSUE TITLE
need support close note by click note titlebar

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#107]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/20a73112-4e0e-4cca-bfcd-1f9bd7a7438c)

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/899754f6-a8dd-4e84-8232-c194be0082cf)

**Comment by Nevysha** [comment]
Added a close btn. You'll need to update through update panel
