### ISSUE TITLE
how to use Cozy Nest Image Browser?

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#108]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/5b757bb7-46ec-462a-8bba-816b2c4bac58)

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/a6b74942-c735-431d-8704-a4cca416ca97)

**Comment by Nevysha** [comment]
I don't understand the second img you pasted. What is it ?

**Comment by bluelovers** [comment]
> I don't understand the second img you pasted. What is it ?

i saw the http request. but in webui area is still empty and show `CONNECTING`

**Comment by Nevysha** [comment]
@EgorSe2003 Do you have any other errors when starting a1111 ? The output you show look more than a consequences than a cause.
