### ISSUE TITLE
Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by VelvetAcidChrist** [Nevysha/Cozy-Nest#109]
Additional Network tab does not open.

Instance info:
version: [v1.2.1]
python: 3.10.6
torch: 2.0.1+cu118
xformers: N/A
gradio: 3.29.0
checkpoint: [3576ae9275]
Cozy Nest: [v2.0.8]

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

Window size: 1920x937

------------------------------

Extensions:

Config-Presets	
Cozy-Nest	
Keep-this-prompt-for-later	
MiDaS	
OneButtonPrompt
Stable-Diffusion-Webui-Civitai-Helper	
a1111-sd-webui-console-log-integrater	
a1111-sd-webui-lycoris	
adetailer	
civitai-shortcut	
clip-interrogator-ext	
gpt-for-automatic1111-webui	
hide-settings-v2-inner			
lora-prompt-tool	
miaoshouai-assistant	
multidiffusion-upscaler-for-automatic1111	
openpose-editor	
posex	
sd-dynamic-prompts	
sd-infinity-grid-generator-script	
sd-model-organizer	
sd-model-preview	
sd-webui-3d-open-pose-editor	
sd-webui-additional-networks	
sd-webui-controlnet	
sd-webui-infinite-image-browsing	
sd-webui-llul	
sd-webui-photopea-embed	
sd-webui-tunnels	
sd_extension-prompt_formatter	
sd_feed		
sd_web_ui_preset_utils	
sdweb-xyplus	
shift-attention	
stable-diffusion-webui-Prompt_Generator	
stable-diffusion-webui-cafe-aesthetic	
stable-diffusion-webui-chatgpt-utilities	
stable-diffusion-webui-conditioning-highres-fix	
stable-diffusion-webui-embedding-merge	
stable-diffusion-webui-images-browser	
stable-diffusion-webui-model-toolkit	
stable-diffusion-webui-promptgen	
stable-diffusion-webui-state	
stable-diffusion-webui-text2prompt	
stable-diffusion-webui-two-shot	
ultimate-upscale-for-automatic1111	
webui-interior-design-style	
LDSR	built-in		
Lora	built-in		
ScuNET	built-in		
SwinIR	built-in		
prompt-bracket-checker	built-in

------------------------------

An error in socket handler
Object of type bytes is not JSON serializable

**Comment by Nevysha** [comment]
Hey
Can you update Cozy Nest (and restart a1111) and see if your issue is solved please ?
