### ISSUE TITLE
loading screen stuck at "Woops, it's taking longer than expected."

### ISSUE THREAD

**Issue by Raivshard** [Nevysha/Cozy-Nest#113]
I don't know how to reopen an existing issue, and it seems like this still needs attention, so here.

original post: https://github.com/Nevysha/Cozy-Nest/issues/50

So.
Deleting browser cookies doesn't seem to fix this. It just went from being stuck at 99% to being stuck at "Woops, it's taking longer than expected."

I'm running vladmandic's branch on Firefox. Tried it on Edge and chrome, too

Oh, and it's spelled "whoops." #sorrynotsorry

here's my extension list:
- a1111-sd-webui-lycoris
- clip-interrogator-ext
- LDSR
- Lora
- multidiffusion-upscaler-for-automatic1111
- prompt-bracket-checker
- ScuNET
- sd-dynamic-thresholding
- sd-extension-system-info
- sd-webui-controlnet
- sd-webui-model-converter
- stable-diffusion-webui-images-browser
- stable-diffusion-webui-rembg
- SwinIR
- Cozy-Nest
- openOutpaint-webUI-extension
- PromptGallery-stable-diffusion-webui
- sd-webui-3d-open-pose-editor
- sd-webui-aspect-ratio-helper
- sd-webui-infinite-image-browsing
- stable-diffusion-webui-embedding-editor
- stable-diffusion-webui-Prompt_Generator
- stable-diffusion-webui-state
- stable-diffusion-webui-tokenizer
- ultimate-upscale-for-automatic1111

I just switched over to vladmandic and have been using it without any (other) issues.
I used cozy with regular automatic. Really like the improved UI. It's completely hung here, though. I'm sad.

**Comment by Nevysha** [comment]
Probably one of those extension is conflicting. Do you know if one of them is extensive on the DOM ? (aside from Cozy Nest 🙃 )

**Comment by Raivshard** [comment]
I do not know. All I can tell you is that I used all of these extensions before with 1111 and while loading was slow, that was not due to cozy nest, and everything did work.

**Comment by Nevysha** [comment]
Hey
Can you update to latest (2.1.2) and see if it works now ? I've downloaded Vlad's fork and fixed few things. It should work now ;)

**Comment by Raivshard** [comment]
Oh, cool! I'll check it out on the weekend when I have time to power
everything back up.

**Comment by Raivshard** [comment]
Works now, thanks!

**Comment by Raivshard** [comment]
... and this problem has returned again.

running latest versions of everything. 

Note: the only reason I updated to the latest sd.next is because the cozy extra networks browser stopped working -- the panel popped out, but nothing loaded. It was working fine last week and I explicitly did not update vlad during that period. Everything but cozy worked fine. I clear the cache every time I exit the webUI, so that is also not the issue.

To be sure, I next installed vlad completely fresh and installed my extensions via the extensions tab, rather than copying them. webUI has been completely closed and started fresh, not just a server restart. Problem persists.
