### ISSUE TITLE
Cozy Image Browser - Some images broken, some with "Error parsing metadata"

### ISSUE THREAD

**Issue by mocmocmoc** [Nevysha/Cozy-Nest#116]
![unAvqpf 1](https://github.com/Nevysha/Cozy-Nest/assets/6404011/94a41ee8-d973-41ae-8a3d-c1af188e2bf4)

![Untitled-221](https://github.com/Nevysha/Cozy-Nest/assets/6404011/ab8581e1-356d-4187-9a86-2f476cc3e7b0)

![d9FSUAS 1](https://github.com/Nevysha/Cozy-Nest/assets/6404011/e0adb292-661a-4dcd-bcd5-510f83fcd049)

**Comment by Nevysha** [comment]
Those images are in a different folder that the others ? (it shoulds work anyway but the process to get them might be bugged). Can you please give me the "src" attribute of one of the bugged image and one which is not ?

**Comment by mocmocmoc** [comment]
Same default folder. 

All images that have "DPM++ SDE Karras" in the filename is broken. 
It is **fixed** when I rename "DPM++ SDE" to "DPM SDE"

--

Broken image
`<img class="cozy-nest-thumbnail" src="http://127.0.0.1:7860/cozy-nest/image?path=C:\AI\A1111 Web UI Autoinstaller\stable-diffusion-webui\outputs\txt2img-images\4060802519-341657225_DPM++ SDE Karras_STP20_CFG4.png" alt="image">`

Working image
`<img class="cozy-nest-thumbnail" src="http://127.0.0.1:7860/cozy-nest/image?path=C:\AI\A1111 Web UI Autoinstaller\stable-diffusion-webui\outputs\txt2img-images\4060802518-3103144235_Euler a_STP20_CFG3.png" alt="image">`

**Comment by Nevysha** [comment]
It should be fixed now !

**Comment by mocmocmoc** [comment]
> It should be fixed now !

Holy cow you're fast. Yup fixed.
