### ISSUE TITLE
The scroll wheel does not work in extra networks

### ISSUE THREAD

**Issue by EgorSe2003** [Nevysha/Cozy-Nest#119]
![Скриншот 23-05-2023 211150](https://github.com/Nevysha/Cozy-Nest/assets/134436554/c8525819-b671-49e8-a5a6-42b578798967)
![Скриншот 23-05-2023 211613](https://github.com/Nevysha/Cozy-Nest/assets/134436554/d514011f-799f-44c4-890a-2640ebd4fb21)
Sorry for my English, I'm using a translator
I have a lot of LoRA downloaded and I can't see them all without using the search bar. I can't scroll through the list
I can see all of LoRA only when opening the list in full screen and minimum element sizes
I use yandex browser

**Comment by Nevysha** [comment]
It's not related to yandex browser, I've tested quickly on it and it works. For troubleshooting, is it possible for you to disable other extension and see if it works ?

**Comment by EgorSe2003** [comment]
Disabling it didn't help in any way, but initially there was no such error. If I remember correctly, this error appeared with the advent of the image browser

**Comment by NinjaDanny87** [comment]
same issue here, I am unable to scroll using Chrome or Opera GX.

gonna hold of on using Cozy until this is fixed.

**Comment by Nevysha** [comment]
I'll work on the 1.3 version update of auto 1111 and redo the extra network from scratch when I'm done with what I'm into atm (image browser, exif editor, rich prompt editor).

**Comment by NinjaDanny87** [comment]
> 

Sounds good, is there a way to hide the image browser side tab as well? It would be nice to hide that. (sorry for the side question)

**Comment by Nevysha** [comment]
The tab is now hidden when you disable it from Cozy Nest settings (v2.2.0)
