### ISSUE TITLE
Image Browser Crash on Search

### ISSUE THREAD

**Issue by ZombieNixon** [Nevysha/Cozy-Nest#121]
Hi,

Love the extension so far!

After updating, things work fine until I use the search feature in the image browser. As soon as a type a letter into the search bar, this error pops up:

![image](https://github.com/Nevysha/Cozy-Nest/assets/60117619/ce8fd88b-c963-4275-8e99-625fe5056f4a)

I'm not seeing any errors for this extension or otherwise in the console. This occurs in Chrome as well. Any help is greatly appreciated.

**Comment by Nevysha** [comment]
Thanks for spoting it. I got a fix that will be shiped in the next update (later today)
