### ISSUE TITLE
Big gap in quicksettings area

### ISSUE THREAD

**Issue by undercovervictory** [Nevysha/Cozy-Nest#124]
I hope this is the right place to post this. Hi, as you can see, there's a space here between my checkpoint and vae bit
![2023-05-25 01_27_05-Window](https://github.com/Nevysha/Cozy-Nest/assets/81896151/880a8786-cc6d-4ba7-99f1-0d3adbb7cf18)

Did I miss a setting somewhere that might fix it? This is in the latest chrome.

**Comment by Nevysha** [comment]
You have to switch the quicksettings position from "split" to another one
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/166bbc36-db1a-42a1-b9be-449619fdc165)
