### ISSUE TITLE
`CozyNest=No` not behaving well

### ISSUE THREAD

**Issue by catboxanon** [Nevysha/Cozy-Nest#125]
The URL parameter `CozyNest=No` as first introduced in https://github.com/Nevysha/Cozy-Nest/releases/tag/v1.2.1 seems to not behave as ideal as it should. As of https://github.com/Nevysha/Cozy-Nest/releases/tag/v2.1.3 (I've not tested on other versions at this point), it still applies the Cozy Nest CSS (perhaps this is unavoidable), but it also prevents scrolling. I've tested this on mobile and on desktop, in both Firefox and Chrome.

**Comment by Nevysha** [comment]
Maybe related to the code refactoring I did from version 2.1. I'll check this. The idea was to also remove any css related to Cozy Nest and it should work that way or it's useless.
