### ISSUE TITLE
[Issue]: Column resizing in txt2img doesn't work

### ISSUE THREAD

**Issue by AltosKey** [Nevysha/Cozy-Nest#131]
### What happened?

Can't resize columns between options and preview in txt2img. All updates are installed and tried in different browsers: Edge, Cent, Opera, Yandex.
![2023-05-27_11-39-02](https://github.com/Nevysha/Cozy-Nest/assets/25365820/033e6ddf-0eee-48d7-8d83-3fef479317d9)
![2023-05-27_12-14-08](https://github.com/Nevysha/Cozy-Nest/assets/25365820/09281267-0cd7-4728-8826-8d9884f9c098)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Chrome

### Additional info

A bug happened!

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
Hey,
For troubleshooting, Can you try without canvas-zoom and NPW ? Thanks
