### ISSUE TITLE
[Issue]: setting still can't load after ui loaded

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#133]
### What happened?

A bug happened!

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional info

im not sure
but this maybe help
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/2fc2fbb4ea34899220b141eb67b9515b433feb71

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
should be fixed in latest (2.3.0)
