### ISSUE TITLE
[Issue]: bad ui display

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#135]
### What happened?

A bug happened!

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/257a1848-323d-40e7-bf65-61af85e74081)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional info

A bug happened!

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
Can you retry on last update please ? (2.3.0)
