### ISSUE TITLE
Extra Tab network and CivitAI helper 

### ISSUE THREAD

**Issue by randykoala** [Nevysha/Cozy-Nest#142]
### What happened?

The CIvitai Helper icons for link to URL, tag words and prompts overlap each other in top right corner of network image thumb so not easy to select

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Chrome

### Additional info

A bug happened!

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by mindturbulence** [comment]
I have the same problem, im using Edge, this happen in a few updates back.

**Comment by thecoolwolf** [comment]
For me the buttons don't show up at all. it is stopping me from using the cozy nest atm. I really hope it can be fixed

**Comment by Nevysha** [comment]
should be fixed in latest (2.3.0)
