### ISSUE TITLE
[Feature]: Option to automatically scale the generated image to fill the frame

### ISSUE THREAD

**Issue by morphinapg** [Nevysha/Cozy-Nest#146]
### Feature description

I have a 4K monitor. When I'm generating 512x512 images, once generation is done, they appear very small until I click them to zoom in. It would be nice if the images automatically filled the frame, like they do mid-generation. When I try to zoom in the entire UI on my screen, the generated image doesn't stay centered, so that doesn't help either (although a fix to that would also be useful here)

I typically start with a 512x512 image, and then use the results of that with ControlNet to generate higher resolution images. The higher resolution images fill the frame just fine, but the 512x512 images are always too small.

**Comment by Nevysha** [comment]
> When I try to zoom in the entire UI on my screen, the generated image doesn't stay centered, so that doesn't help either (although a fix to that would also be useful here)

I'm trying to avoid the need of zooming entirely so I prefer to work on why users have to zoom ;)

Regarding your main request, is it possible that you make a quick exemple of what you want ? (make a screenshot and edit it, even poorly)

**Comment by morphinapg** [comment]
> > When I try to zoom in the entire UI on my screen, the generated image doesn't stay centered, so that doesn't help either (although a fix to that would also be useful here)
> 
> I'm trying to avoid the need of zooming entirely so I prefer to work on why users have to zoom ;)
> 
> Regarding your main request, is it possible that you make a quick exemple of what you want ? (make a screenshot and edit it, even poorly)

I agree it would be best if I didn't need to adjust the zoom level of my browser. Even when I have the browser only taking up half my screen, the images are still small.

Here's how it looks currently:

https://images2.imgbox.com/ea/ec/fcKyQd74_o.png

Here's what I'd like it to look like:

https://images2.imgbox.com/1f/ba/7eihNyfy_o.png


I have all this screen space, I'd like to use it :)

Like I said, it could just be an optional setting. Right now once the image is generated I can click it and it fills the screen, but I'd rather just have it fill the space it's occupying which would save me a click.

**Comment by Erehr** [comment]
In A1111 main folder add this to user.css

```
#txt2img_gallery img, #img2img_gallery img, #extras_gallery img {
    object-fit: contain;
}
```

**Comment by morphinapg** [comment]
> In A1111 main folder add this to user.css
> 
> ```
> #txt2img_gallery img, #img2img_gallery img, #extras_gallery img {
>     object-fit: contain;
> }
> ```

This works! Thank you :)
