### ISSUE TITLE
[Issue]: image browser does not work when running on a port other than 7680

### ISSUE THREAD

**Issue by the0ckid82** [Nevysha/Cozy-Nest#149]
### What happened?

A bug happened!

### Webui

Vlad's fork webui (SD.Next)

### What browsers are you seeing the problem on?

Firefox, Chrome, Something else (please specify)

### Additional info

it appears that in the image browser port 7680 is hard coded so if you choose to run SD on any other port the image browser will fail to show any images 

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
Not sure what you means. Are you talking about the gradio app port ? 7680 is the default port for gradio app. The image browser run a socket on another one

**Comment by the0ckid82** [comment]
yes the gradio app if you run it on anything else other than 7680 when you use the cozy image browser the image path points to port 7860 instead of what ever port you are running it on. screenshots below show sdnext running on port 7862, and the image browser knows that the images exist how ever when it trys to load the thumbnails or the image it is trying to get them on the default gradio port 

image being generated 

![image](https://github.com/Nevysha/Cozy-Nest/assets/5402500/895f7721-168f-4549-a18b-efc8486f15ab)

cozy image browser

![image](https://github.com/Nevysha/Cozy-Nest/assets/5402500/761d5ed6-ccc0-4b3c-8bc9-d4bf3ddef23a)

large view of image

![image](https://github.com/Nevysha/Cozy-Nest/assets/5402500/8a1d5027-440d-4d47-bd41-787709f7ea58)

inspecting via devtools showing its looking on the wrong port 

![image](https://github.com/Nevysha/Cozy-Nest/assets/5402500/bff6d7ce-8d8e-4701-8b80-591e389fe9d2)

hope this helps explain what i mean

**Comment by Nevysha** [comment]
ah yes you are totally right. I'll fix that
