### ISSUE TITLE
[Feature]: Prompt Weighting via Ctrl + Up / Down in prettified prompt box?

### ISSUE THREAD

**Issue by Fenrir200678** [Nevysha/Cozy-Nest#150]
### Feature description

Hi there!

Would you mind adding the prompt weighting via Ctrl + Up / Down in the prettified prompt box? Currently this doesn't work (at least for me). It only works in the native text area.

Regards,
Fen

**Comment by Raivshard** [comment]
yeah, the prettified text area really only has one use right now: checking that your brackets are all where they should be.

**Comment by DrJKL** [comment]
Looks like [this is in](https://github.com/Nevysha/Cozy-Nest/commit/18cbb8484ec060d019987ca97baed4d4c9a27427#diff-0672dde0f8f5460af148d86b5aea6e507a46aaf6d82b4df7f6492e9b41ca52d2R205).

**Comment by Nevysha** [comment]
Yes it is ! thanks for clarifying for others ;)
