### ISSUE TITLE
Cannot scroll 

### ISSUE THREAD

**Issue by NinjaDanny87** [Nevysha/Cozy-Nest#153]
### What happened?

When opening the extra networks tab where LoRA's and models are stored, I am unable to scroll using the mouse wheel, or finding any side bar to scroll down the list. Search is the only one that works and is quite fiddly to use.

Using the latest version.

### Webui

Vlad's fork webui (SD.Next)

### What browsers are you seeing the problem on?

Something else (please specify)

### Additional info

Browsers tested in:

Chrome, Opera GX, EDGE,

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
DROPPING SUPPORT FOR SD.NEXT. Cozy Nest is now only compatible with Automatic1111's webui. Maintaining compatibility with SD.Next was too much work for me. I'm sorry for the SD.Next users.

**Comment by NinjaDanny87** [comment]
> DROPPING SUPPORT FOR SD.NEXT. Cozy Nest is now only compatible with Automatic1111's webui. Maintaining compatibility with SD.Next was too much work for me. I'm sorry for the SD.Next users.

does that include Vlad's fork of A1111? they are basically the same....

**Comment by NinjaDanny87** [comment]
> DROPPING SUPPORT FOR SD.NEXT. Cozy Nest is now only compatible with Automatic1111's webui. Maintaining compatibility with SD.Next was too much work for me. I'm sorry for the SD.Next users.

well, that sucks.... looks like I won't be following this repository anymore. smh

**Comment by Nevysha** [comment]
fyi in fixed it faster than I though and sd next support is back in 2.3.2
