### ISSUE TITLE
[Feature]: cozy nest+ Civitai-Helper

### ISSUE THREAD

**Issue by Tsuka-N7** [Nevysha/Cozy-Nest#155]
### Feature description

Hello your extension is really great it is one of my favorites! My only problem is that since the last update of your extension, some features of the Civitai Helper extension no longer work: Modified Built-in Extra Network cards, to add the following buttons on each card:
🖼️: Modified "replace preview" text into this icon
🌐: Open this model's Civitai url in a new tab
💡: Add this model's trigger words to prompt
🏷️: Use this model's preview image's prompt

So I can't update your extension, the new features look cool it would be really great if you could do something about it.

In any case, thank you for your extension, it's a great job!

**Comment by Nevysha** [comment]
On it for the next update ;)

![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/bebaab1b-3292-48ea-9af3-fa1f17995013)

**Comment by Nevysha** [comment]
should be fixed in latest (2.3.0)

**Comment by Tsuka-N7** [comment]
awesome you are the best thank you !
