### ISSUE TITLE
[Issue]: `CozyNest=No` forcing site in desktop mode

### ISSUE THREAD

**Issue by catboxanon** [Nevysha/Cozy-Nest#156]
### What happened?

Appending `CozyNest=No` works in that it disables CozyNest, however this forces the UI to always display in desktop mode. The site will no longer adapt to mobile device sizes (this can be tested with something like Responsive Design Mode in Firefox). Disabling the CozyNest extension fixes this issue.

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Firefox, Chrome

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
should be fixed as of 2.4.3
