### ISSUE TITLE
Please add a transparent / dark background to the live preview pane

### ISSUE THREAD

**Issue by wzol** [Nevysha/Cozy-Nest#16]
During live preview the picture pane turns white which is not too comfortable in a dark theme. I believe it only needs this change:

```
.livePreview {
    background-color: initial;
}
```

**Comment by Nevysha** [comment]
I did not reproduce this bug. I've added the code you gave me. Can you please update and see if it fix your issue ?

**Comment by wzol** [comment]
I have a faster live preview display setting so maybe that is the reason. - Thank you for the quick fix!
It seems the fix is not good enough, as now you can see through the live preview background - which is only visible if the previously used aspect ratio is quite different - like from portrait to landscape.
Could you try:

```
.livePreview {
    background-color: var(--background-fill-primary);
}
```

This should probably respect other palettes too.

Also the thumbnails border color not visible, I suggest:

```
.thumbnail-small.selected.svelte-g4rw9.svelte-g4rw9 {
    --ring-color: var(--color-accent);
    transform: scale(1);
    border-color: var(--ae-primary-color);
}
```

Also Img2img pane is bit buggy, could you try:

```
#txt2img_actions_column, #img2img_actions_column {
    gap: 0.5em;
    width: 100%;
    flex: none;
    order: 1;
}
```

And finally "Show/Hide Generation Info" doesn't seem to work on Img2Img - could you check it?
