### ISSUE TITLE
[Issue]: No lines with Prompt and Negative prompt

### ISSUE THREAD

**Issue by SteveM50** [Nevysha/Cozy-Nest#161]
### What happened?

A bug happened! The lines with Prompt and Negative prompt, which also have the function of splitting inserted prompts, are not visible. not even if I switch off the cozy promptly. I use Chrome

![CozyNestError](https://github.com/Nevysha/Cozy-Nest/assets/14312645/181e8a1e-3902-4458-9a05-f5d69436db53)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Chrome

### Additional info

A bug happened!
![CozyNestError2](https://github.com/Nevysha/Cozy-Nest/assets/14312645/9f365cb7-bb62-4ea9-8bc8-b2aaa8f364a1)

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
I'm sorry but I don't understand what you are talking about. Can you provide a screenshot without CozyNest of what you expect ?

**Comment by SteveM50** [comment]
sorry for my bad writing. Here are the button that i mean. this error is only **with** magic prompt
![CozyNest OK](https://github.com/Nevysha/Cozy-Nest/assets/14312645/b96e62f6-dbd3-4475-983f-b5bdaf3363f2)
![CozyNestError2](https://github.com/Nevysha/Cozy-Nest/assets/14312645/be36d4e6-987a-47d8-b472-24b44840a2de)

**Comment by Nevysha** [comment]
It's under the main prompt "Redo last prompt"

**Comment by SteveM50** [comment]
ohh, thx
