### ISSUE TITLE
[Issue]: Infinite "Extra Network" loads

### ISSUE THREAD

**Issue by Cenc0n** [Nevysha/Cozy-Nest#166]
### What happened?

Extra Network won't load, can't use Lora, etc.

![IouPIho3SGY](https://github.com/Nevysha/Cozy-Nest/assets/138619960/6e267587-c3e8-4e2b-922a-a3d2be07d71d)
![image](https://github.com/Nevysha/Cozy-Nest/assets/138619960/7adc5b95-eca8-4743-99e9-78535bb79ba5)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Chrome

### Additional info

Previously, this panel didn't load sometimes, after the last update it stopped loading at all
![image](https://github.com/Nevysha/Cozy-Nest/assets/138619960/7c2ef95d-e43d-4568-9018-0739a9a079d6)

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Trahloc** [comment]
Having similar issue on Vladmandic. I only have the infinite loading screen and don't see the ghosted images but I just added Cozy Nest so perhaps I lack cache to show those.

**Comment by Nevysha** [comment]
I'm reworking this panel in next version (lots of work but nearly done)

**Comment by Nevysha** [comment]
Please try the new update and tell me if it's better now !

**Comment by Cenc0n** [comment]
> Please try the new update and tell me if it's better now !

It works! Thank you! ⸜(*ˊᗜ ˋ*)⸝
