### ISSUE TITLE
Overlapping extension & model text at low browser size

### ISSUE THREAD

**Issue by Goatle** [Nevysha/Cozy-Nest#17]
Noticed this because I have way too many extensions installed.

If your window is not fullscreen and you have a lot of extensions the text will overlap from the model dropdown and extension. This makes the extension unclickable. Tested on Firefox.

![image](https://user-images.githubusercontent.com/9473724/236590387-2de13ce8-9650-46fd-bc64-036c5684b6bc.png)

**Comment by Nevysha** [comment]
I'll look into it. Until that you can maybe use the left sided menu settings ?

**Comment by Nevysha** [comment]
Moreover, I plan to add a feature which will enable to Drag and Drop tab button inside or outside a “tab container” to bring them or move them from/out main menu. It should be easier to daily use than the "hide tab" native option of auto1111.

**Comment by gsgoldma** [comment]
> I'll look into it. Until that you can maybe use the left sided menu settings ?

left side cuts off after a certain number of extensions with no scrolling, son one would have to zoom out just to see the other extension tabs.

**Comment by Nevysha** [comment]
I'll add a scroll both for vertical and horizontal menu

**Comment by Chr1s330** [comment]
same problem on the phone if I use the share link to use webui

**Comment by R-ES-H** [comment]
As a temporary fix I edited the style.css in the extension folder with 
```
.gradio-container.app.menu-fix-top {
    margin-top: 50px !important;
}
```
instead of 25px

**Comment by Nevysha** [comment]
I just release an update. There is now a workaround for user having too many tab as you there is an "other" menu added in which you can drop tab button to gain some space. It may be buggy at first start when you have to much tab already but it provide a good alternative imo. There is also the native "hide tab" settings.
