### ISSUE TITLE
[Issue]: models, lora, and lyco previews not showing

### ISSUE THREAD

**Issue by roll0ver** [Nevysha/Cozy-Nest#171]
### What happened?

Hypernetworks and textual inversion previews showing as before but after the last update the other categories show as if I have no preview files in there when I do.

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Additional info

Even if I set a preview, it does not display.

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
Can you update through extensions tab and then relaunch ui with param `--cozy-nest-debug` please ? You should see something like this : 
```
[Cozy:ExtNe:DEBUG] FILE_DIR: D:\stable-diffusion\stable-diffusion-webui
[Cozy:ExtNe:DEBUG] EXT_PATH: D:\stable-diffusion\stable-diffusion-webui\extensions
[Cozy:ExtNe:DEBUG] EMB_PATH: D:\stable-diffusion\stable-diffusion-webui\embeddings
[Cozy:ExtNe:DEBUG] HYP_PATH: D:\stable-diffusion\stable-diffusion-webui\models\hypernetworks
[Cozy:ExtNe:DEBUG] LORA_PATH: D:\stable-diffusion\stable-diffusion-webui\models\Lora
[Cozy:ExtNe:DEBUG] LYCO_PATH: None
[Cozy:ExtNe:DEBUG] MODEL_PATH: D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion
```
Which settings are you using between those : 
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/064725cf-c7a8-4b48-b68e-95f86e6ff1c5)

**Comment by roll0ver** [comment]
The paths from the debug are correct, and as I said Textual Inversions and Hypernetwork display as normal. My settings match yours, tweaks off, extra network on.

**Comment by roll0ver** [comment]
![image](https://github.com/Nevysha/Cozy-Nest/assets/108014021/367922e0-c489-42e2-842d-31281bfaeb27)

**Comment by dcostap** [comment]
Having the same issue. 

While the Extra Networks tab is loading, these errors are thrown in javascript:
![image](https://github.com/Nevysha/Cozy-Nest/assets/37813277/56e2054a-a0ef-4d8f-827f-8d029a05a140)

**Comment by Nevysha** [comment]
this error is not relevent to CozyNest but to system info extension (and you're probably on SD Next ?)

**Comment by roll0ver** [comment]
I figured this out, looks like you added *.preview.png to I used power rename to add that to my exisiting .png files.
