### ISSUE TITLE
[Issue]: Missing button

### ISSUE THREAD

**Issue by DemitriLatet** [Nevysha/Cozy-Nest#181]
### What happened?

where is this button? 
![kozy-button](https://github.com/Nevysha/Cozy-Nest/assets/7502693/932aff5d-abca-42f0-bc96-0d6f4d685cb3)

New interface
![kozy-missing](https://github.com/Nevysha/Cozy-Nest/assets/7502693/fa64b3e9-0c8f-482c-9c2f-4ee80c1d960b)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
That was the "Redo last prompt" button. I replaced it with the same arrow icon in last update (which you can by updating through extension tab)
