### ISSUE TITLE
"Show/Hide Generation Info" doesn't work in img2img

### ISSUE THREAD

**Issue by HardeNNN** [Nevysha/Cozy-Nest#19]
It's permanently stuck open...

**Comment by Ev-Bro** [comment]
Came here for this. Happening to me too. Check in Firefox and Chrome.

**Comment by Nevysha** [comment]
Will check later. I'm afk for few days.

**Comment by Ev-Bro** [comment]
Thanks

**Comment by Nevysha** [comment]
I just release an update, your issue should be fixed in the new version !

**Comment by Ev-Bro** [comment]
Working now! Thanks.
