### ISSUE TITLE
[Issue]: A1111 1.6 broke the UI

### ISSUE THREAD

**Issue by gharmonica** [Nevysha/Cozy-Nest#192]
### What happened?

The new update of SD webui broke CozyNest's UI to the point of it being unusable.

![Screenshot 2023-09-01 130330](https://github.com/Nevysha/Cozy-Nest/assets/42785687/40a474b8-d856-4e2d-97ff-f28ed2676ace)
![Screenshot 2023-09-01 130311](https://github.com/Nevysha/Cozy-Nest/assets/42785687/acbda2ca-a83d-4eaa-804d-cc3f8668af73)

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Chrome

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by LadyFlames** [comment]
i cant use it either like nothing works  everything is broken including extensions because of 1.6.0 all we have to do is wait for an update when ever thats gonna come

**Comment by sujeet2555** [comment]
Having the same issue. outpur window box is not in side but down. Ui is just resizing constantly.

**Comment by Narcromancer** [comment]
I too am having the constant resizing issue, as well extension update seems to never load installed extensions to the list. 
![Opera Snapshot_2023-09-03_160431_127 0 0 1](https://github.com/Nevysha/Cozy-Nest/assets/137659212/994e1f2f-4923-4caf-990f-3d9cc4359a90)
![Opera Snapshot_2023-09-03_160452_127 0 0 1](https://github.com/Nevysha/Cozy-Nest/assets/137659212/ca77c1f2-3242-4ff8-b45d-74cb3d4e7770)

**Comment by melschue** [comment]
Having the same issue. Under Chrome also Ui is just resizing constantly. Works a little bit better under Firefox. Also presets are broken.

**Comment by LadyFlames** [comment]
theres also the problem of Text dissappearing and half of the text vanishing from the prompt box in both txt to image and img2img

**Comment by madrooky** [comment]
Yes totally broken right now. Confirm all above. Not usable.

**Comment by LadyFlames** [comment]
yea id say they need to make updating  this Broken thing a Númber 1 priority everything else that comes after is secondary now  that error shows up now as well  Failed to connect to github.com port 443 after 21109 ms: Couldn't connect to server' along with a whole bunch of other failed to connect ones i know for a fact its not my internet  causing that issue

**Comment by mocmocmoc** [comment]
From Discord, the dev mentioned he's too damn busy at the moment. Might take a while to fix but hopefully soon.

**Comment by LadyFlames** [comment]
![error](https://github.com/Nevysha/Cozy-Nest/assets/137729901/32d4a24e-0f5c-4fb2-ad25-ef8ef0ef6d9e)
oh boy

**Comment by AsuraAce** [comment]
> ![error](https://user-images.githubusercontent.com/137729901/268792704-32d4a24e-0f5c-4fb2-ad25-ef8ef0ef6d9e.png) oh boy

delete Cozy and reinstall it, should fix this problem.

**Comment by R3D5W1P3** [comment]
> delete Cozy and reinstall it, should fix this problem.

That's the first thing I tried 2 weeks ago but it did nothing to help. Just did it again on the off chance it might work but it's still busted.

**Comment by LadyFlames** [comment]
![Problems](https://github.com/Nevysha/Cozy-Nest/assets/137729901/9835a7ce-0849-474c-b3a3-bc1d4bd0fb79)
this is how it looks with it being Broken Doesnt happen everytime it happens  like every 22Hours it turns into being like that otherwise its working Okay minus the Vanishing/Dissappearing Text Issue

**Comment by Nevysha** [comment]
Drop a quick update to start to fix for newest version of A1111 ;)

**Comment by mocmocmoc** [comment]
> Dropped a quick update to start to fix for newest version of A1111 ;)

THANK YOU!
I realise I can't comfortably use A1111 anymore without your extension!
