### ISSUE TITLE
[Feature]: 🙏SD.Next (Vlad) rework

### ISSUE THREAD

**Issue by esbe1175** [Nevysha/Cozy-Nest#195]
### Feature description

SD.Next is awesome for many reasons, but horrible for one main reason; The UI.

Cozy does a _lot_ already, but there are so many glaringly obvious UI/UX design atrocities in SD.Next that Cozy in it's current state just doesn't cover some very needed things.

I know I'm asking for a lot, because indeed the UI just _is_ that different on SD.Next as compared to A1111. Regardless, I hope and pray that the **one** UI with any real current compatibility considerations, might be able to fix things up and make them.. cozy. I and a lot of others would be incredibly thankful.

**Comment by Nevysha** [comment]
Heya
I barelly have the time to work on Cozy Nest for a1111 so I won't support SD Next anytime soon. Note that SDN team is working on its own ui and I may work on it in the future
