### ISSUE TITLE
When several images are generated, the currently selected image needs a pixel border

### ISSUE THREAD

**Issue by intuitive-arts-ai** [Nevysha/Cozy-Nest#2]
When several images are generated, the currently selected image needs a pixel border to know which one is. It seems to be missing.
Example: generate a batch of 4 images in txt2img, and then select one. It doesn't have a highlight border in the small thumb.

**Comment by boog2dan** [comment]
pls look into it. when generating img variants (10+) it is almost impossible to know when we reached the end
