### ISSUE TITLE
Inpaint expand bug

### ISSUE THREAD

**Issue by ostap667inbox** [Nevysha/Cozy-Nest#20]
A minor bug that occurs when you delete an image in the expanded state in the Inpaint tab. How to repeat:
1. Open the inpaint tab. Load the image there.
2. Press 'Expand' to open image full screen.
3. In the expanded state, delete the image with the 'x' button. Press 'Reduce' to return to the normal state.
4. Load another image. Press 'Expand' - expand no longer happens, each press of 'Expand' displays an error in the console.

**Comment by Nevysha** [comment]
Button will be hide when in full screen
