### ISSUE TITLE
BUG: Unable to access scripts.

### ISSUE THREAD

**Issue by Miyuutsu** [Nevysha/Cozy-Nest#21]
Screenshot attached to showcase issue. Simply will not extend down far enough. Issue is present on both txt2img and img2img.  Happens even with all other extensions disabled only in img2img. Have not tested other tabs. Tested in Firefox, Vivaldi and Chromium. python 3.10.11, gradio 3.28.1, torch 2.1, latest webui commit at time of writing. Resizing browser causes even more stuff to be cut off, native resolution 2560x1440. Linux, but I don't think this should make a difference for web rendering. 

![image](https://user-images.githubusercontent.com/20072970/236639781-86b3c082-1073-4cf1-9c18-8a6b6cd3c8da.png)

**Comment by Nevysha** [comment]
May be related to the number of script. I'll look into it.

**Comment by Miyuutsu** [comment]
I've confirmed this issue also happens in the PNG info tab if there's too many prompts. The buttons down below end up cut off.

**Comment by Miyuutsu** [comment]
https://github.com/Nevysha/Cozy-Nest/issues/22

This issue led to me trying 60% which seems to make everything visible as well, but mine isn't Firefox related.

**Comment by Nevysha** [comment]
Hey
Are you still having this issue in last update ? I tried with more than 100 script bloc and I did not have the bug. Maybe you have another extension that conflict with Cozy-Nest ?
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/c513ba6d-ca4a-47a8-80b7-16fbdbc9c59a)

**Comment by Miyuutsu** [comment]
It will be at least a couple days before I will be able to get to my computer to test. I can at least confirm it is still present on this commit: https://github.com/Nevysha/Cozy-Nest/commit/db94a7860da728df4463ba2eeb2411bcb0148e9a

Since I tested it with all other extensions disabled, I would like to think it is unrelated to any others. If it's still present when I'm able to update and check, I'll let you know and provide a list of all dependencies and versions since there's the possibility mine may differ as well. I do not think it's browser related since I tried in Vivaldi, Chromium and Firefox.

Is it possible it's a font issue? I'm running Linux and I know that can occasionally cause some font headaches.

**Comment by Miyuutsu** [comment]
I've managed to confirm the cause of the issue. It's related to my quick settings. Two screenshots attached showing my img2img tab as well as my extensions tab. I decided it worthwhile to to set my quick settings to match what appeared to be yours for testing and I was able to access my scripts. My quick settings where it causes this for reference: 

`sd_model_checkpoint, sd_checkpoint_cache, sd_vae_checkpoint_cache, sd_vae, img2img_fix_steps, eta_noise_seed_delta, save_images_before_highres_fix, extra_networks_default_multiplier, upscaler_for_img2img, uni_pc_order, uni_pc_variant, CLIP_stop_at_last_layers, face_restoration_model`

In my attempt to replicate yours where scripts was accessible I simply used:

`sd_model_checkpoint`

Happens on Firefox, Chromium and Vivaldi. Happens with an without extensions. Happens whether I have the window maximized or not and I'm running at 2560x1440. Setting page size to 60% makes them accessible but of course very small.

![Screenshot_20230511_132914](https://github.com/Nevysha/Cozy-Nest/assets/20072970/61b6cd62-8ea7-4f8e-9574-9f78009fc491)
![Screenshot_20230511_132954](https://github.com/Nevysha/Cozy-Nest/assets/20072970/e3269964-7466-4e4d-9625-ac1b0c4c483a)

**Comment by Nevysha** [comment]
OK I got it ! thanks a lot for the troubleshooting and detailed reproduction step ! I'll look into a fix for it.

**Comment by Miyuutsu** [comment]
I see there's been some progress so I wanted to update you. I can now access my scripts without issue, but it seems the upper part of the UI is now cut off even when ensuring I'm scrolled all the way up.
![image](https://github.com/Nevysha/Cozy-Nest/assets/20072970/c92febe5-432d-42f0-88d4-3ea1f2526550)

I also had a new unrelated issue but I haven't been able to reproduce it so I haven't yet made an issue for it. When accessing my settings panel I got the following error:
![Screenshot_20230515_133955](https://github.com/Nevysha/Cozy-Nest/assets/20072970/b8b39019-2ee6-4747-b62f-9f340c6d923e)

**Comment by Nevysha** [comment]
So many quicksettings ! Please copy/paste your quicksettings options 
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/2fa9968c-cb33-4c4c-9bae-2fb038c77624)

**Comment by Miyuutsu** [comment]
> So many quicksettings ! Please copy/paste your quicksettings options ![image](https://user-images.githubusercontent.com/122687716/238478537-2fa9968c-cb33-4c4c-9bae-2fb038c77624.png)

Sorry for the late response. I have copy pasted them before. I didn't realize the WebUI had changed the way they input so I'll space them out.

```
sd_model_checkpoint

sd_checkpoint_cache

sd_vae_checkpoint_cache

sd_vae

img2img_fix_steps

eta_noise_seed_delta

save_images_before_highres_fix

extra_networks_default_multiplier

upscaler_for_img2img

uni_pc_order

uni_pc_variant

CLIP_stop_at_last_layers

face_restoration_model
```

**Comment by Nevysha** [comment]
I've pushed a small fix/workaround. Quicksetting now have a max height and a scroll. (2.0.6)

**Comment by Miyuutsu** [comment]
Thanks for all the work on this, I can successfully access everything now!
