### ISSUE TITLE
Extra Networks sidebar toggle (Enhancement)

### ISSUE THREAD

**Issue by Vodrin** [Nevysha/Cozy-Nest#23]
Please consider making the 'close extra networks tab' button a permanent toggle. 

Ie; always a thin button at the side that pressing opens the extra network tab and pressing again closes the extra network tab.

A setting to maintain current functionality could be added "[x] Extra Networks sidebar toggle"

Thank you for any consideration

**Comment by Nevysha** [comment]
It will be in the next version 

![image](https://user-images.githubusercontent.com/122687716/236642806-0e65ead9-7255-4f40-840c-e6d02e3f223f.png)

**Comment by Nevysha** [comment]
I just release an update, your issue should be fixed in the new version !
