### ISSUE TITLE
T2I can't display...

### ISSUE THREAD

**Issue by shinomiyaaoi** [Nevysha/Cozy-Nest#25]
Any advice? Just in Text2Image, Both in Edge and Chrome.Display correct without the plugin.
Thank you.
![image](https://user-images.githubusercontent.com/58676272/236651359-b6e18429-29bd-453a-b1d1-3d51cff4e4ce.png)
![image](https://user-images.githubusercontent.com/58676272/236651466-8fd74b0d-77f7-4007-bcd2-dc720126e0ab.png)

**Comment by Nevysha** [comment]
Do you have other extension ? Please provide your extension list and your web browser name

**Comment by shinomiyaaoi** [comment]
Thanks for reply.
![image](https://user-images.githubusercontent.com/58676272/236660893-c2a21d65-0472-430c-b9b5-ec4b11c9cdbe.png)
And This browser is Edge, and chorme is same as Edge.

**Comment by Nevysha** [comment]
Probably one of those conflict with Cozy Nest. I won't go through the whole liste sorry.

If you are able too find which one is concerned and it's a popular one you can reopen and I may take a look.

**Comment by shinomiyaaoi** [comment]
Yes,off all extension ,and work,thanks for you help.
