### ISSUE TITLE
Conflict with queue extension

### ISSUE THREAD

**Issue by Trevor-Z** [Nevysha/Cozy-Nest#26]
This extension and SDAtom-WebUi-client-queue-ext don't seem to play well with each other, when both are active the other one stays on top of the UI elements and breaks the layout.

Here's the repo: https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext

**Comment by Nevysha** [comment]
Every extension acting strongly on the dom may break everything. Not sur if I can do anything about that
