### ISSUE TITLE
Can i use with the Anapnoe Fork? I know its inspired on it but i wanna try

### ISSUE THREAD

**Issue by FutonGama** [Nevysha/Cozy-Nest#27]
When i try to use this happens.
![firefox_0YXbCRdNPa](https://user-images.githubusercontent.com/95169493/236725412-2ab86d0b-020a-46f2-a4a5-ecd543478ad0.png)

I tried to remove his sd_theme_editor extension and i also tried to change Style.css for the style of A1111 and no luck, is not loading.

**Comment by Nevysha** [comment]
Nope it will not work. I'll add a better handling of error. Atm you can manually delete the Cozy Nest extension folder manually
