### ISSUE TITLE
[enhancement] The extra networks panel should retract whenever you click outside of it

### ISSUE THREAD

**Issue by Mozoloa** [Nevysha/Cozy-Nest#31]
As the title suggests, having to go to the extreme right of the screen to close it is pretty annoying and it's hiding a great par of the UI. 

Most of what I do is I select the extra network then go to modify the weigh or just click generate. With the original layout the panel can stay there it's not in the way, but here we have one more click now, and it's at the opposite of where we want to be with our mouse.

**Comment by Nevysha** [comment]
Personnaly I prefer to close it myself as I keep it open while tweaking other setting and prompt. But I'm adding a settings to enable to behavior you're talking about in the next version.

**Comment by zopi4k** [comment]
personally I'm not convinced that the panel should retract ... if you have to do several Lora / text inversion it quickly becomes painful. For my part, it might be to put the close button in the center of the adjustable bar on its left side while leaving the dots visible for the resizing.

**Comment by Nevysha** [comment]
Oh that's a really neat idea !

**Comment by Nevysha** [comment]
So, I'll not add a setting but I like the proposition from @zopi4k . Along with it I'll add a listener on the escape keyboard key to close it when pressed

**Comment by Nevysha** [comment]
The update is live !

**Comment by Mozoloa** [comment]
Thank you, I also pressed escape all the time at first, this is going to be better ! Also my window was probably too wide
