### ISSUE TITLE
Overlapping

### ISSUE THREAD

**Issue by Jaulustus** [Nevysha/Cozy-Nest#32]
i have some extensions and there a many tabs 
![TSvyZxM](https://user-images.githubusercontent.com/8465385/236962149-bdb0e899-a866-4971-94fc-2ac5dec4d0ea.png)
now its overlapping

**Comment by hexx1001** [comment]
![image](https://user-images.githubusercontent.com/50043926/237011575-480645f2-2e70-4885-9383-f1d7239d9ed9.png)

**Comment by hexx1001** [comment]
Here is a sample of reduced width effect when using my mobile to access with the UI. Wonder if it can be made to dynamically adjust based on different screen sizes so that it is usable on mobile devices too.

<img width="300" alt="screenshot" src="https://user-images.githubusercontent.com/50043926/237012470-cde45611-241e-4690-8ff3-09bece7120db.png">

**Comment by zopi4k** [comment]
Hello [Jaulustus](https://github.com/Jaulustus) ;) Do you have the new version ? you can put your list of tab inside the "others" tab ^^)
![img](https://user-images.githubusercontent.com/131191891/237015049-f48e14d0-fdde-4f09-ac2a-cb7a08420045.jpg)

For the problem of [hexx1001](https://github.com/hexx1001) it's brok when the navitor pass 1185px of width
![img2](https://user-images.githubusercontent.com/131191891/237015861-532e3b46-3620-43f2-b83a-d0151db537c6.jpg)

**Comment by Nevysha** [comment]
I'm sorry but I won't support mobile. I'm adding a workaroud to bypass CozyNest easyly by adding "CozyNest=No" in the URL

**Comment by Nevysha** [comment]
The update is live. You can now Bypass CozyNest on your mobile by adding `CozyNest=No` in URL from your mobile. As for @Jaulustus , please update. You can either use the Cozy Nest feature to drag and drop tab inside "Others" or use the native "hide tab" feature from a1111.
