### ISSUE TITLE
little problem :) amazing potential! +suggestions

### ISSUE THREAD

**Issue by bryanray** [Nevysha/Cozy-Nest#36]
quicksetting little problem:
![image](https://user-images.githubusercontent.com/1768531/237032278-130c2614-9d25-4125-ad9b-50ff66634604.png)

suggestion:
add a button to turn on and off this extentsion?
it will let user quick switch back and forth and not intruding workflow, until this extension reach maximum potential :)

love you

**Comment by bryanray** [comment]
another little issue: this button do nothing not closing window
![image](https://user-images.githubusercontent.com/1768531/237033989-2ea0a340-cf8d-4841-9216-bbbbc68b3f19.png)

**Comment by bryanray** [comment]
adding stuffs like these to settings menu,  which i having proposing to vlad+anpoe 
![image](https://user-images.githubusercontent.com/1768531/237034604-95e60c1e-c431-477d-8ca1-fb2f44185aaf.png)

this guy makes it, WIP
https://github.com/vladmandic/automatic/pull/638

**Comment by zopi4k** [comment]
this btn is to drag the panel ... yes, I think it's not realy userfull ... I don't use it myself.
![237033989-2ea0a340-cf8d-4841-9216-bbbbc68b3f19](https://user-images.githubusercontent.com/131191891/237035911-9af3ca97-c46f-4a1d-a029-24d9ee92caaa.png)

**Comment by Nevysha** [comment]
I'm using it to see settings change when modifying them.
You can turn off Cozy Nest by adding CozyNest=No in the url

**Comment by zopi4k** [comment]
Or change the picture into "drag" for more comprehension ^^)
![img5](https://github.com/Nevysha/Cozy-Nest/assets/131191891/e45ffa15-f93a-4ab4-8ac4-84393e88929d)
And get your panel smaller with a more compact reorganization ^.^)v

**Comment by Nevysha** [comment]
Will do!
