### ISSUE TITLE
All the buttons have no text, all the tabs are gone, extensions tab is inaccessible, url command to turn off is not working

### ISSUE THREAD

**Issue by iLEZ-iLEZ** [Nevysha/Cozy-Nest#47]
![image](https://github.com/Nevysha/Cozy-Nest/assets/55014378/10919158-5bf8-4d96-8718-8a39015aa42a)
After installing CozyNest all the text in the UI buttons are gone and all tabs are gone, and I can't turn it off temporarily by using the supplied URL variable.

**Comment by iLEZ-iLEZ** [comment]
Running this on a Windows 11 machine by the way. 
Attaching an image of my installed extensions.
![image](https://github.com/Nevysha/Cozy-Nest/assets/55014378/86c6a705-2fcd-427a-b71b-271044c91294)

**Comment by Nevysha** [comment]
Try without stable diffusion webui ux

**Comment by iLEZ-iLEZ** [comment]
> Try without stable diffusion webui ux

Immediate success! Thank you very much.
