### ISSUE TITLE
Poor performance running on foreground

### ISSUE THREAD

**Issue by mustang651** [Nevysha/Cozy-Nest#49]
Hi.
After the last update, I noticed that SD runs 3 times slower on my GTX 1080 when Cozy Nest is opened in the foreground. According to the task manager, it uses about 10% of the 3D engine at idle. Maybe it is these waves at the bottom of the page? Can I disable it?

**Comment by mustang651** [comment]
ok, so I rerun the test, and it's not a 3x difference now but still pretty noticeable. The impact depends on quicksettigs position. Here's the results of 4 runs:

1. Position left, opened tab
2. Position left, tab switched
3. Position split, opened tab
4. Position split, tab switched

![2023-05-12-21-22-52_cmd](https://github.com/Nevysha/Cozy-Nest/assets/19196847/247b224c-9471-42e2-a2db-acde59f108fb)

**Comment by mukolah** [comment]
Can confirm that gradient animation is loading GPU substantially, would be nice having button to disable all animations. Here is a very rough but quick fix to disable animations (also stops loading circle so I guess I overdid it a bit) but most importantly reduced idle load to 0% (literally) when Auto1111 is open and focused.

Open: **stable-diffusion-webui\extensions\Cozy-Nest\style.css**
And comment following lines:

- Line 622

`/*animation: gradient 35s ease infinite;*/`

- Line 648 and 649

```
/*animation: wave 10s -3s linear infinite;
transform: translate3d(0, 0, 0);*/
```

- Line 658

`/*animation: wave 18s linear reverse infinite;*/`

- Line 664

` /*animation: wave 20s -1s reverse infinite;*/`

- Block at line 668

```
/*@keyframes wave {
    2% {
        transform: translateX(1);
    }
    ... ....
    100% {
        transform: translateX(1);
    }
}*/

```

- Line 1180

`/*animation: lds-roller 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;*/`


- Block at line 1249

```
/*@keyframes lds-roller {
    0% {
        transform: rotate(0deg);
    }
    100% {
        transform: rotate(360deg);
    }
}*/
```

After that **save styles.css** and **restart Auto1111**. Should be fixed.

**Comment by mustang651** [comment]
Thanks! And yes, you don't need to disable the roller.

**Comment by Nevysha** [comment]
I'll add a settings to disable background animation (gradiant + waves)
The next update is tacking time so please be patient ! 💙

**Comment by Chilluminati91** [comment]
was about to uninstall due to the ever so slight input lag, removing the waves fixed it! thanks @mukolah

**Comment by Nevysha** [comment]
should be customizable in setting in version v2.0.2 (live now!)
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/8baed124-6a29-433c-9093-06b8d68587b1)
