### ISSUE TITLE
Loading menu stuck on 99% Indefinitely.

### ISSUE THREAD

**Issue by dstructx** [Nevysha/Cozy-Nest#50]
Dear [nevysha],

I am writing to report a bug that I encountered while using your UI extension, "Cozy Nest." While navigating through the tabs, I noticed that some of them disappeared.

In an attempt to fix the problem, I reloaded the UI, but this only caused the loading menu to get stuck on 99%. Unfortunately, despite waiting for an extended period, the loading menu never progressed beyond this point. I have checked all my settings and made sure that my system is up to date, I tried to reinstall your extension by first uninstalling it via the extension tab and then deleting the correlating folder from the web UI extensions file directory but after reinstalling the extension the problem still persists.

I believe that this bug is preventing me from using the extension effectively and I would appreciate it if you could look into it as soon as possible. I am happy to provide any further details that may be useful in resolving the issue.

Thank you for your prompt attention to this matter.

Best regards,

[dstructx] xoxoxo

**Comment by Nevysha** [comment]
Hello, please provide your extension list and the browser you're using

**Comment by dstructx** [comment]
I fixed the issue by deleting the Krita extension"[auto-sd-paint]" and then reinstalling your extension. 
Here is the information you requested in case you find it helpful. 

Internet Browser: Edge. 

This is my extension list before the fix: "
"sd-webui-ar"
"sd-webui-controlnet"
"ultimate-upscale-for-automatic1111"
"Config-Presets"
"Cozy-Nest"
"auto-sd-paint"

I am going to try and reinstall the Krita extension once more. I am happy to provide more information upon request. If you don't hear from me all is well, thank you.

**Comment by MonkeyDocs** [comment]
> I fixed the issue by deleting the Krita extension"[auto-sd-paint]" and then reinstalling your extension. Here is the information you requested in case you find it helpful.
> 
> Internet Browser: Edge.
> 
> This is my extension list before the fix: " "sd-webui-ar" "sd-webui-controlnet" "ultimate-upscale-for-automatic1111" "Config-Presets" "Cozy-Nest" "auto-sd-paint"
> 
> I am going to try and reinstall the Krita extension once more. I am happy to provide more information upon request. If you don't hear from me all is well, thank you.

I too having this infinite loading issue on Edge (first happened on Edge), Google Chrome works for now

**Comment by MonkeyDocs** [comment]
> Please try this temp fix : [#41 (comment)](https://github.com/Nevysha/Cozy-Nest/issues/41#issuecomment-1544755025)

![Screenshot21](https://github.com/Nevysha/Cozy-Nest/assets/61049870/4ab29713-f0fd-4e44-ac97-b79d0dbe96a5)
Hm still loading infinitely

**Comment by Raivshard** [comment]
Deleting browser cookies doesn't seem to fix this. It just went from being stuck at 99% to being stuck at "Woops, it's taking longer than expected."

I'm running vladmandic's branch

here's my extension list:
- a1111-sd-webui-lycoris
- clip-interrogator-ext
- LDSR
- Lora
- multidiffusion-upscaler-for-automatic1111
- prompt-bracket-checker
- ScuNET
- sd-dynamic-thresholding
- sd-extension-system-info
- sd-webui-controlnet
- sd-webui-model-converter
- stable-diffusion-webui-images-browser
- stable-diffusion-webui-rembg
- SwinIR
- Cozy-Nest
- openOutpaint-webUI-extension
- PromptGallery-stable-diffusion-webui
- sd-webui-3d-open-pose-editor
- sd-webui-aspect-ratio-helper
- sd-webui-infinite-image-browsing
- stable-diffusion-webui-embedding-editor
- stable-diffusion-webui-Prompt_Generator
- stable-diffusion-webui-state
- stable-diffusion-webui-tokenizer
- ultimate-upscale-for-automatic1111

**Comment by Nevysha** [comment]
> I'm running vladmandic's branch on Firefox 

I'm not actively supporting compatibility for vladmandic atm
