### ISSUE TITLE
Styles menu is cutoff just below "Generate" button

### ISSUE THREAD

**Issue by prog0111** [Nevysha/Cozy-Nest#52]
One of the changes recently moved the list of styles below the pos/neg prompts (which is nicer), but with a very long list of styles, the list that pops up will get hidden behind the Generate button.  It's not possible to scroll the list to see or select the blocked styles.  The issue seems to be present both on automatic1111 as well as the vladmandic fork.  I'm running Chrome.

I've made the following user.css to fix this on my end for now:

#txt2img_styles label > div > ul,
#img2img_styles label > div > ul {
  bottom: auto !important;
  border-width: 4px !important;
  border-color: var(--nevysha-dark) !important;
}
#txt2img_styles label > div > ul {
  max-height: 335px !important;
}
#img2img_styles label > div > ul {
  max-height: 260px !important;
}

Forcing the bottom property to auto makes the list open downwards rather than upwards.  Forcing it's max height gives it a reasonable size - otherwise you'll have to scroll the entire left panel downwards in order to see all of the styles listed.  I'm not sure if this is how it's intended to look, but maybe it can be helpful to show what I changed.

**Comment by Nevysha** [comment]
fixed in release 2.0.2
