### ISSUE TITLE
The menu and content of "Hires.fix" are not fully displayed

### ISSUE THREAD

**Issue by adsamalu4kia** [Nevysha/Cozy-Nest#53]
The expanded items or options in the "Hires.fix" menu are not being displayed even when clicking the checkboxes.
![FireShot Capture 011 - Stable Diffusion - 127 0 0 1](https://github.com/Nevysha/Cozy-Nest/assets/71839219/fd704659-fb42-4e81-b3d8-b1450da0ee54)

**Comment by nullip** [comment]
The txt2img_hires_fix css id seems to not toggle the hidden flag

**Comment by Nevysha** [comment]
It work on my side :/
Can you chech the value of this settings and give me the result please : 
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/055715a9-0390-4f32-9adb-42ec3a93b4bd)

**Comment by Nevysha** [comment]
Not checked : 

![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/1b619ced-b720-4ae9-a6c1-8ecba51694cd)

<hr>
Checked : 

![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/da91c536-24eb-45e7-b233-bd65d0928a93)
