### ISSUE TITLE
txt2image generate not working

### ISSUE THREAD

**Issue by SteveM50** [Nevysha/Cozy-Nest#55]
and the cozy-nest menu disappears immediately. other menu items work (probably)

**Comment by SteveM50** [comment]
I have uninstalled and reinstalled cozy-nest. the generate works now. but the menu disappears immediately.

**Comment by Nevysha** [comment]
I don't understand what you are talking about. Can you provide more information as well as screenshot and step to reproduce ? Also please provide a1111 commit number and your extension list.
