### ISSUE TITLE
`save` Cozy-Nest setting not work

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#56]
when click save, after reload ui, setting is reset

**Comment by bluelovers** [comment]
looks like saved setting is never use

when i edit `def get_default_settings()`, it also not work

**Comment by Nevysha** [comment]
As wrote in the known issue : 
> If setting are saved and user refresh, it will revert to old setting (only visually) because webui load them at gradio launch

**Comment by bluelovers** [comment]
i think should reload setting after ui init once
