### ISSUE TITLE
bug: preview too small and can't be click view when pnginfo open

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#58]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/386a0008-9896-4d00-934d-056439917ef2)

**Comment by Nevysha** [comment]
You can close gen info to get it back ?
What may be a good UI fix for this issue in your opinion ?

**Comment by mukolah** [comment]
Resolved in dev branch (commit #62)
![StyleTest](https://github.com/Nevysha/Cozy-Nest/assets/1958477/ad67e61c-a267-4914-9b3a-0ea4d5882863)

**Comment by Nevysha** [comment]
fixed with latest release
