### ISSUE TITLE
txt2img tab - frames broken on Chrome and Firefox

### ISSUE THREAD

**Issue by Sharknaad0** [Nevysha/Cozy-Nest#61]
Cozynest ver: https://github.com/Nevysha/Cozy-Nest.git/commit/24e04cc4d7ab9cb310b4a8990798a99e5fb89874

txt2img unusable on Chrome and Firefox
all other tabs working correctly

Chrome Version 113.0.5672.93
Screenshot:
![screenshot](https://github.com/Nevysha/Cozy-Nest/assets/114832875/722d5d5f-9770-4788-af97-2807ca1a18d2)

Firefox Ver 113.0.1
Screenshot:
![firefoxscreenshot](https://github.com/Nevysha/Cozy-Nest/assets/114832875/af454c5b-aac3-4947-a941-a18701d70459)

**Comment by Nevysha** [comment]
Can you provide the following info please : 
- Auto1111 commit hash
- List of installed and activated extensions

**Comment by Sharknaad0** [comment]
Current hash: b08500cec8a791ef20082628b49b17df833f5dda

(was also broken on previous hash)

Extensions installed:
![image](https://github.com/Nevysha/Cozy-Nest/assets/114832875/6cd53ca2-d058-417e-be9f-2bff71f23296)

**Comment by Sharknaad0** [comment]
Removed several extensions and was able to get txt2img to render correctly.
