### ISSUE TITLE
Bug: The settings panel in the upper right always shrinks automatically after it is expanded

### ISSUE THREAD

**Issue by aaronfang** [Nevysha/Cozy-Nest#66]
Browser: chrome
webui version: 1.2.0 ( happend in v1.1.0 as well )

Starting from a certain version days ago, every time I click the setting panel button in the upper right corner, it shrinks automatically after it expands, making it impossible for me to modify and save the settings.

**Comment by R-ES-H** [comment]
I had this too but it disappeared somehow, I think it's related to the anchor
Also there is no scroll on the settings and patchnote windows, Save/Reload/Reset are hidden for me, a quick fixfor this is 
```
.nevysha-tab-settings {
    height: 100%;
   overflow:auto;
}
```
line 1148

**Comment by SteveM50** [comment]
same

**Comment by renealex-lurks** [comment]
Same.
(Firefox add-ons deactivated, and also in edge on the same machine)
the cloud update info button woks as expected, just the settings auto close at activation.

**Comment by Nevysha** [comment]
Fixed in last update
