### ISSUE TITLE
Cozy Nest 2.0 Image Browser causing trouble

### ISSUE THREAD

**Issue by madrooky** [Nevysha/Cozy-Nest#67]
So i installed this UI just a few days ago and i love it. But a few minutes ago i installed the latest update and the new feature causes issues. I am sorry if i missed some information that is posted somewhere, but at least here on git hub i cant find anything.
And with some things related to this complex topic around SD i am relatively inexperienced and just a user who needs a bit of explanation.

1) It cannot connect to the Web Socket, what ever and where ever that is, i dont know because i cant find any further information about it. 

2) There is no option to turn it off, or did i miss something?

3) It spams the console when generating images, probably because the Web Socket is not connecting. 

4) Perhaps because the problems with the Web Socket, it breaks image generation after one run. I mean it does not generate images any more. 

And since i cannot find any information about the recent change i am not going for a trouble shoot on my own because i am a noob when it comes to this specific aspect of the matter. But maybe some one is able to help out or at least my post lets the creators know that there is an issue.
Luckily there is an older version on civitai, i just removed the new one and tried the older and it seems to work without any issues.
Maybe it would be good to have information about such updates as soon as they are made available.

Thanks for making this UI.

cheers

**Comment by Alyndiar** [comment]
I concur! This update makes the extension nearly unusable as is, I will have to disable for now. Too bad because this made the UI so much better, expecially for inpainting

**Comment by madrooky** [comment]
> I will have to disable for now. 

Dont forget that there is an older version available:
https://civitai.com/models/62325/cozy-nest

But for me it just stopped working too, does not finish loading the UI. It worked for a while though, its weird...

**Comment by Nevysha** [comment]
I'm on it

**Comment by mocmocmoc** [comment]
For me the CozyImageBrowser is just blank, nothing shows up.
I'm also using the ImageBrowser extension.

**Comment by wzol** [comment]
Hm, same here and not even see it in the extensions list anymore.

**Comment by Nevysha** [comment]
> I'm also using the ImageBrowser extension. 

They does not conflict... Atm I don't know why so many people have problem with the 2.0.0 ><*

I'm working on a way to disable image browser via settings and fixing a case where the socket is not properly closed on UI reload

**Comment by mukolah** [comment]
FYI you can always download previous versions in the release tab of GitHub, it is not recommended to use sources outside of GitHub or the Extensions tab for downloads to avoid malicious code.
https://github.com/Nevysha/Cozy-Nest/releases

Can confirm it does flood the console with logs but does not break generation, I have Image Browser installed and can generate images continuously. I installed an update manually from GitHub by replacing the files because the update using "cloud" icon failed for me, maybe there's something wrong with that.

**Comment by Nevysha** [comment]
I just pushed [v2.0.1](https://github.com/Nevysha/Cozy-Nest/releases/tag/v2.0.1)

**Comment by madrooky** [comment]
> I installed an update manually from GitHub by replacing the files because the update using "cloud" icon failed for me, maybe there's something wrong with that.

Good point, i updated that way and it seemed to work. Gonna do a fresh install and see what happens. 

Btw, the civitai release is apparently from Nevysha, isnt it?
Maybe the author can confirm it. But its alright to be careful with sources. I got to admit i did not think about that,

**Comment by Nevysha** [comment]
>Btw, the civitai release is apparently from Nevysha, isnt it?

Yup it's me

**Comment by madrooky** [comment]
> > Btw, the civitai release is apparently from Nevysha, isnt it?
> 
> Yup it's me

Thanks for the update btw. I installed now the latest version again from git, and it seems to work now. Good thinking to disable the browser by default. I activated it and it works. Meanwhile i had even a problem with the 1.2.3, wasnt loading gui any more. But never mind it works now, thanks again. :)

Only one thing i find confusing, when i installed the gui first time 2 days ago, i found it in the extension tab of a1111. But you wrote you did not push it yet. Or did you remove it again?
cheers

**Comment by Nevysha** [comment]
>Only one thing i find confusing, when i installed the gui first time 2 days ago, i found it in the extension tab of a1111. But you wrote you did not push it yet. Or did you remove it again?

I published it but has not updated the README accordingly

**Comment by wzol** [comment]
Thank you for the amazingly quick fix, but is it normal that I don't see it on the extensions page and can't install it from there? Previously I thought I messed up something so I deleted the extension folder.

**Comment by madrooky** [comment]
> Thank you for the amazingly quick fix, but is it normal that I don't see it on the extensions page and can't install it from there? Previously I thought I messed up something so I deleted Cozy from the extension folder.

That why i asked too. Its gone from there now. But you can just copy the url from the main page here and use "install from url" tab in the extension. I just did that and it works.
https://github.com/Nevysha/Cozy-Nest

**Comment by wzol** [comment]
It did the install as said, but I got an error which I never seen before. Did I mess up something?

<img width="1229" alt="image" src="https://github.com/Nevysha/Cozy-Nest/assets/11561358/8a3b969b-878a-4fc9-a063-4aac8c4d4335">

**Comment by Nevysha** [comment]
> It did the install as said, but I got an error which I never seen before. Did I mess up something?

I added an error handler to Cozy Nest so it's easier for me when people post bug on github as they just have to paste the image here. You can disable it from Cozy Nest settings.

In this case it does not look linked to Cozy Nest.

regarding extensions tab, that's because they tagged as "ads" since there is my ko-fi link. So you have to uncheck "ads" when fetching extensions
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/0e356381-0387-4345-8905-318dd6198b31)

**Comment by wzol** [comment]
Oh, I see, from now on I won't forget checking ads ;)

**Comment by Nevysha** [comment]
it's "hide extensions with tags..." so you have to uncheck it ;)
