### ISSUE TITLE
Bug: The extra networks panel on the right side cannot be expanded in the txt2img tab

### ISSUE THREAD

**Issue by aaronfang** [Nevysha/Cozy-Nest#68]
The extra networks panel on the right side cannot be expanded in the txt2img tab, but it can be expanded and retracted normally in the img2img tab.

BTW, Cozy image browser can be expanded normally in both tabs.

**Comment by SteveM50** [comment]
same

**Comment by mukolah** [comment]
Please press on the "wand" on top-right corner, then click on "click here to gather relevant info" and provide the screenshot. It will contain most of information necessary to reproduce the issue. I'm running both Chrome and Firefox latest and works just fine, however I have minimal extension setup so it's most likely extension conflict.

**Comment by aaronfang** [comment]
here's the screenshot
![chrome_uSNTAKL3sZ](https://github.com/Nevysha/Cozy-Nest/assets/349068/292830f4-55d4-4c38-ae71-e74d004542bb)

**Comment by Nevysha** [comment]
Can you try to update to https://github.com/Nevysha/Cozy-Nest/releases/tag/v2.0.1 please ?

**Comment by rubensicko** [comment]
I don't have a scroll bar either, I also use the civitai helper extension. Can it be fixed? I think before v2 it worked fine.

**Comment by mocmocmoc** [comment]
"The extra networks panel on the right side cannot be expanded in the txt2img tab"

I went into Settings and just click Save Settings and Reload UI and that fixes it.
A1111 has new feature "When adding to prompt, refer to lora by Alias from file or Filename", it is defaulted to "Alias from file"

Not sure if related.

**Comment by Duemellon** [comment]
cool WebUI but not quite ready for my usage. I have many Loras & need that scrollbar to work in Chrome. Tried restarting UI but didn't fix it. Disabled the Cozy for now
