### ISSUE TITLE
Cozy Image Browser error

### ISSUE THREAD

**Issue by mocmocmoc** [Nevysha/Cozy-Nest#71]
![eE9CMBx](https://github.com/Nevysha/Cozy-Nest/assets/6404011/cf858ca9-5157-4b8d-a27b-fea5f09cd5d9)

**Comment by Nevysha** [comment]
Should be fixed in v2.0.2 update 

> - [x] Fix image browser crash if metadata are not formatted as expected (although metadata display may display "Error parsing metadata")
