### ISSUE TITLE
additions button

### ISSUE THREAD

**Issue by Sotonya** [Nevysha/Cozy-Nest#74]
![2](https://github.com/Nevysha/Cozy-Nest/assets/117153969/812d0b64-63a5-45ca-88db-d767fb2f5dbe)
where is the button for displaying additions: Laura, textual inversions, etc...

**Comment by Nevysha** [comment]
this menu is on the right part of your screen 
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/993314da-ce70-46b7-b16e-7451cc88b6ba)

**Comment by Sotonya** [comment]
oh, thanks!
