### ISSUE TITLE
High CPU load with Firefox

### ISSUE THREAD

**Issue by ogurikaz** [Nevysha/Cozy-Nest#77]
Issue/Question:

Really like the look of this extension, but for some reason it makes firefox consume high cpu resources as long as the tab is in focus. (Going to another tab in the same firefox window reduces the cpu usage again).

Looking at the network tab in developer console it seems to update something about each second, which is not the case when not using the extension. (See image).
![Untitled](https://github.com/Nevysha/Cozy-Nest/assets/46486419/10485a13-08c9-4c84-b9be-72c6d0d8d672)

PS: I have deactivated the image browser.

Not sure if this is a known problem or if anyone else is getting this.

**Comment by mukolah** [comment]
It is known issue that was fixed: https://github.com/Nevysha/Cozy-Nest/issues/49#issuecomment-1546943206
Open settings using the magic wand, put a checkmark on "Disable waves and gradient background" hit "Save" and you will see your CPU usage go down to 0% :)

**Comment by ogurikaz** [comment]
> It is known issue that was fixed: [#49 (comment)](https://github.com/Nevysha/Cozy-Nest/issues/49#issuecomment-1546943206) ...

Thanks, this did reduce CPU use a bit, but not completely (compared to not using the extension).

Maybe it's expected for the extension to use a bit of resources continuously even at idle?

**Comment by Nevysha** [comment]
It should not
