### ISSUE TITLE
Bug: Choosing a new checkpoint sometimes results in a second checkpoint change being inexplicably chosen/queued 

### ISSUE THREAD

**Issue by wwboynton** [Nevysha/Cozy-Nest#80]
Action: Select new checkpoint from the top drop-down menu
Expected Behaviour: Load that checkpoint
Actual Behaviour: That checkpoint is loaded, and then immediately following that, another checkpoint is loaded from the menu instead.

I can't find any pattern to this. I can reproduce it reliably enough if I change my checkpoint several times, but it doesn't happen every time. It also doesn't seem to choose the same unintended second checkpoint each time. 

```
python:
3.9.16
 •  torch: 2.0.0+cu117  •  xformers: N/A  •  gradio: 3.28.1  •  commit:
[00bbd4bf](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/00bbd4bff153970802defaa20f33eaba84816008)
 •  checkpoint:
[7f6146b8a9](https://google.com/search?q=7f6146b8a9ad2a92b739954c1d5ef34e26fb0b65eef2d70ffd128e6046a3d0ab)
```

**Comment by wwboynton** [comment]
Adding to this: It seems like perhaps the drop-down is actually getting visually hidden but not closed, as interacting with some parts on the right half of the UI as a checkpoint is loading can cause the checkpoint selection drop-down menu to suddenly reappear. It's possible that it's just not closing, so attempting to click pieces of the left-hand side of the UI actually results in clicking the checkpoint menu again without any visual indication as such.

**Comment by Nevysha** [comment]
I doubt it's related to Cozy Nest. I did not change anything regarding this
