### ISSUE TITLE
CozyNest causing SD to fail to start

### ISSUE THREAD

**Issue by Arthur-McArthur** [Nevysha/Cozy-Nest#81]
Startup is stuck and I am getting a: 

RuntimeError: File at path C:\AI\SD\sdwebui\extensions\Cozy-Nest\assets\images\ui-icons_777777_256x240.png does not exist.

**Comment by Nevysha** [comment]
Please do the following : 
- update extension
- restart SD webui completely
- Refresh web browser without cache `ctrl+shift+r`

**Comment by Nevysha** [comment]
Fixed in current version
