### ISSUE TITLE
top menu block quicksetting

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#86]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/c7680b3b-0698-4c1a-9006-54ef76b6cdff)

should be like 

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/be03a57a-7a89-4836-b96f-91518fffa7ab)

or

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/6e814342-e130-4ed2-8351-d60b8e126eae)

**Comment by Nevysha** [comment]
Are you using all those tab ? You can drag them inside the "Others" panel.

**Comment by bluelovers** [comment]
i mean quicksetting is not full disply , because top menu block it

![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/ec899303-862a-4e1a-89c1-edf37ce3302e)

**Comment by Nevysha** [comment]
OK I understand, that's because the top menu is not made to properly handle bigger text for tab name like in your screenshot. I'll look into it

**Comment by Nevysha** [comment]
What extension are you using to have you UI in chinese (I guess :3) ? I had never used localization on a1111

**Comment by lolvivianli** [comment]
i'm experiencing the same issue as well, the extension is called sd-webui-bilingual-localization

**Comment by Nevysha** [comment]
Can you try updating through extension tab please ? I made a quickfix

**Comment by Nevysha** [comment]
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/ce866b31-3b1d-4a84-be61-70159b4b88e5)
