### ISSUE TITLE
bottom padding cutting off Extensions that is placed under the preview window

### ISSUE THREAD

**Issue by mocmocmoc** [Nevysha/Cozy-Nest#9]
There's also a huge gap in the quick settings panel

![Untitled-1](https://user-images.githubusercontent.com/6404011/236083363-23f6b0ad-d6b8-4450-911a-627ec92d4938.jpg)

**Comment by Nevysha** [comment]
Thanks for the screenshots !

The gap between checkpoint and other quicksettings are done on purpose. But since a lots of people are confused with it I'm going to add a setting to disable it.

I'll look into the other issue you are showing in the next update

**Comment by Nevysha** [comment]
Turns out that those extension are wrapped behind the "Show/Hide Generation Info" button. But I can't see it on your screenshot (should be in the bottom of the image viewer). What browser are you using ? And what is your current webui commit hash and gradio version please ?

**Comment by mocmocmoc** [comment]
Gradio: 3.28.1
Commit: 5ab7f213
Browser: Google Chrome

Cheers!

**Comment by Nevysha** [comment]
should be fixed it the new update.
