### ISSUE TITLE
LoRa, Checkpoint, etc.. browser missing

### ISSUE THREAD

**Issue by ronmurphy** [Nevysha/Cozy-Nest#90]
Browser: Edge Dev
OS: Windows 11
Python 3.10.10
Cozy-Nest version: v2.0.0

Issue: The Lora/Checkpoint/etc 'browse' button simple is not there.

![image](https://github.com/Nevysha/Cozy-Nest/assets/4020360/e67fa4e3-50c1-4790-a5cc-bed10dce95ac)

**Comment by mukolah** [comment]
Hi! First, it is highly recommended to [update to v2.0.2](https://github.com/Nevysha/Cozy-Nest/releases/tag/v2.0.2) as v2.0.0 was unstable for many users.
As per your question, please see: https://github.com/Nevysha/Cozy-Nest/issues/74#issuecomment-1546944203
There should be "Extra networks" button on the right side of the screen.

**Comment by VelvetAcidChrist** [comment]
When using ?CozyNest=no button is also missing in the old design
