### ISSUE TITLE
after updating to 2.0.2, ... css issue? idk. see pic.

### ISSUE THREAD

**Issue by ronmurphy** [Nevysha/Cozy-Nest#95]
used the built in extension updater, closed the browser, stopped SD, and then rebooted, and then re-started SD and the browser ... and the CSS is wonky?
![image](https://github.com/Nevysha/Cozy-Nest/assets/4020360/87a0d65e-b1ba-4db3-a1d2-5fa06613ccc0)

**Comment by ronmurphy** [comment]
updated to 2.0.4, issue still persists, i have disabled my only extension (ublock) and it still persists, even after a restart of SD

**Comment by CesarCruzUtec** [comment]
It also happens to me, I've disabled it for now and it's ok again.

**Comment by bluelovers** [comment]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/3135d29e-22ff-4299-8f64-446f6729c8ed)

**Comment by gharmonica** [comment]
A fresh install fixed it for me

**Comment by Nevysha** [comment]
I pushed a new version (2.0.5) which should fix this.

@gharmonica 
> A fresh install fixed it for me

That happen if you manually edit the style.css. Update may not properly works since git will not erase your fix which may conflict with new version of Cozy Nest.

**Comment by bluelovers** [comment]
reset style.css didn't fix for me
