### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by jpoonlua** [Nevysha/Cozy-Nest#96]
OS: Windows 11
Browser: Chrome
Branch: dev

Going to the extensions tab brings this error,<br>
<img src="https://i.snipboard.io/c0PGWU.jpg">
<img src="https://i.snipboard.io/b3T9kW.jpg">

**Comment by jeffrey2212** [comment]
Add a question mark here 

    // set an id for the tab from its text
    tab.id =
      tab.innerText?.toLowerCase()
        //remove all non-alphanumeric characters
        .replace(/\s/g, '_')
        //remove numbers
        .replace(/[0-9]/g, '')

**Comment by jpoonlua** [comment]
> Add a question mark here
> 
> ```
> // set an id for the tab from its text
> tab.id =
>   tab.innerText?.toLowerCase()
>     //remove all non-alphanumeric characters
>     .replace(/\s/g, '_')
>     //remove numbers
>     .replace(/[0-9]/g, '')
> ```

After adding question mark, error is gone but the extensions page has infinite loading
<br>
<img src="https://i.snipboard.io/6M9piG.jpg">

**Comment by Nevysha** [comment]
With that number of extension, one of them is likely to conflict with Cozy Nest :/
