### ISSUE TITLE
Extra Networks Menu not opening on Firefox 

### ISSUE THREAD

**Issue by gharmonica** [Nevysha/Cozy-Nest#98]
Pressing the Extra Networks button doesn't open its Menu. since v2.0.6. Cozy Image Browser menu not affected.

Tested on Chrome and it's working as intended, but not on Firefox.

**Comment by mindturbulence** [comment]
in my case its the opposite., i primary use Edge but i cant open extra networks menu too in all my Chromium based browser.
Tested on Edge, Chrome, Opera, Opera GX and Yandex, but Firefox seems fine

**Comment by WildSlowpoke** [comment]
Same, just updated to 1.2 auto and now extra tab isn't opening with cozy-nest. I'll see if firefox works for me in a bit

**Comment by Nevysha** [comment]
Can you check the cmd output for error (the one with a1111 output, not the browser). Sometime I got error related to Lora on startup but I don't thinks it's linked to Cozy Nest, and maybe your problem is totally different.

Btw Cozy Nest should work on latest a1111 version.

**Comment by WildSlowpoke** [comment]
> Can you check the cmd output for error (the one with a1111 output, not the browser). Sometime I got error related to Lora on startup but I don't thinks it's linked to Cozy Nest, and maybe your problem is totally different.
> 
> Btw Cozy Nest should work on latest a1111 version.

Sorry I'm not the most knowledgable about all this stuff so I'm going to try and understand. Do you mean in the command prompt window is there an error when pressing the extra network tab, if so, there isn't. But if you mean something else, maybe you can explain and I'll look it up

**Comment by Nevysha** [comment]
I mean this black window that show when you launch the webui
![image](https://github.com/Nevysha/Cozy-Nest/assets/122687716/8d0c916f-50fa-4f97-860a-230a7b7712d4)

**Comment by WildSlowpoke** [comment]
I don't get any errors on the cmd console when I hit the extra network menu, but this only happens on Chrome. Firefox doesn't seem to have the issue, but like I said, there aren't any errors popping up

**Comment by Nevysha** [comment]
This is strange since I'm mainly using chrome when working on Cozy Nest :/ . I reproduced a similar bug where sometimes the Extra Network panel don't open and I have to restart the webui to make it work...

Can you try the following : 
- on chrome, when on Cozy Nest : it `CTRL + Shift + R` to reload without the browser cache
- close Chrome
- restart Automatic's webui entirely
- check if your issue is still there

Thanks a lot for your help troubleshooting this

**Comment by xmeta** [comment]
I am having the same problem.
It works in Microsoft Edge but not in Brave.
`CTRL + Shift + R ` and deleting the cache did not solve the problem.

**Comment by xmeta** [comment]
I found a solution to this problem.
I clicked on the button to reset permissions and the problem was resolved.

https://support.brave.com/hc/en-us/articles/360018205431-How-do-I-change-site-permissions-

**Comment by xmeta** [comment]
In my case, I found that the cause of this problem is the use of this extension.

https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk

**Comment by wzol** [comment]
I don't have that extension, nor AdBlockers. Extra Networks only opens in img2img but nothing happens in txt2img - no error. Newest Edge stable.
