### ISSUE TITLE
Drop down menus in quicksettings show a slider instead of dropping down over the rest of the page

### ISSUE THREAD

**Issue by gharmonica** [Nevysha/Cozy-Nest#99]
When checkpoint menu is pressed, a slider shows up, and the drop down menu is not visible unless you scroll down.

![image](https://github.com/Nevysha/Cozy-Nest/assets/42785687/a58705b5-8ba8-42d6-8fa6-68d0e68fb54a)

![image](https://github.com/Nevysha/Cozy-Nest/assets/42785687/b8ae5020-2714-4d67-a642-bdfbf8524e2a)

**Comment by Nevysha** [comment]
I just reverted the quicksettings max height... Should be good in 2.0.7
